// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using automatedexam.Models;

namespace automatedexam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210207071212_newschemaadded")]
    partial class newschemaadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("automatedexam.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("examArticle")
                        .HasColumnType("TEXT");

                    b.Property<string>("examTitle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("automatedexam.Models.Example", b =>
                {
                    b.Property<int>("exampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("exampleId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("automatedexam.Models.answer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("answerText")
                        .HasColumnType("TEXT");

                    b.Property<int?>("questionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("questionId");

                    b.ToTable("answer");
                });

            modelBuilder.Entity("automatedexam.Models.question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ExamId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("correntAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("questionText")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("question");
                });

            modelBuilder.Entity("automatedexam.Models.answer", b =>
                {
                    b.HasOne("automatedexam.Models.question", null)
                        .WithMany("answers")
                        .HasForeignKey("questionId");
                });

            modelBuilder.Entity("automatedexam.Models.question", b =>
                {
                    b.HasOne("automatedexam.Models.Exam", null)
                        .WithMany("questions")
                        .HasForeignKey("ExamId");
                });

            modelBuilder.Entity("automatedexam.Models.Exam", b =>
                {
                    b.Navigation("questions");
                });

            modelBuilder.Entity("automatedexam.Models.question", b =>
                {
                    b.Navigation("answers");
                });
#pragma warning restore 612, 618
        }
    }
}
