// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using automatedexam.Models;

namespace automatedexam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210206014016_tableupdate")]
    partial class tableupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("automatedexam.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("examArticle")
                        .HasColumnType("TEXT");

                    b.Property<string>("examTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("question1")
                        .HasColumnType("TEXT");

                    b.Property<string>("question1AnswerA")
                        .HasColumnType("TEXT");

                    b.Property<string>("question1AnswerB")
                        .HasColumnType("TEXT");

                    b.Property<string>("question1AnswerC")
                        .HasColumnType("TEXT");

                    b.Property<string>("question1AnswerD")
                        .HasColumnType("TEXT");

                    b.Property<string>("question1CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("question2")
                        .HasColumnType("TEXT");

                    b.Property<string>("question2AnswerA")
                        .HasColumnType("TEXT");

                    b.Property<string>("question2AnswerB")
                        .HasColumnType("TEXT");

                    b.Property<string>("question2AnswerC")
                        .HasColumnType("TEXT");

                    b.Property<string>("question2AnswerD")
                        .HasColumnType("TEXT");

                    b.Property<string>("question2CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("question3")
                        .HasColumnType("TEXT");

                    b.Property<string>("question3AnswerA")
                        .HasColumnType("TEXT");

                    b.Property<string>("question3AnswerB")
                        .HasColumnType("TEXT");

                    b.Property<string>("question3AnswerC")
                        .HasColumnType("TEXT");

                    b.Property<string>("question3AnswerD")
                        .HasColumnType("TEXT");

                    b.Property<string>("question3CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.Property<string>("question4")
                        .HasColumnType("TEXT");

                    b.Property<string>("question4AnswerA")
                        .HasColumnType("TEXT");

                    b.Property<string>("question4AnswerB")
                        .HasColumnType("TEXT");

                    b.Property<string>("question4AnswerC")
                        .HasColumnType("TEXT");

                    b.Property<string>("question4AnswerD")
                        .HasColumnType("TEXT");

                    b.Property<string>("question4CorrectAnswer")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("automatedexam.Models.Example", b =>
                {
                    b.Property<int>("exampleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("exampleId");

                    b.ToTable("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
